### ISSUE TITLE
panic: No Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by domingusj** [CanopyTax/ckube#10]
### Expected behavior
The `ckube nodes`, `service`, `deployment`, and `exec` commands should return appropriate info for each command. The `logs`, `ls`, `top`, and `help` commands are working as expected. 

### Actual behavior
`./ckube nodes`
```
panic: No Auth Provider found for name "gcp"

goroutine 1 [running]:
github.com/canopytax/ckube/util.GetClientset(0xc4200a59c0, 0x1b, 0x0)
	/Users/justind/go/src/github.com/canopytax/ckube/util/k8s.go:101 +0xdb
github.com/canopytax/ckube/cmd.nodeMap(0x10afb90e00)
	/Users/justind/go/src/github.com/canopytax/ckube/cmd/nodes.go:83 +0x64
github.com/canopytax/ckube/cmd.printNodeView()
	/Users/justind/go/src/github.com/canopytax/ckube/cmd/nodes.go:28 +0x7b
github.com/canopytax/ckube/cmd.glob..func5(0x24ca3c0, 0x24f6578, 0x0, 0x0)
	/Users/justind/go/src/github.com/canopytax/ckube/cmd/nodes.go:23 +0x20
github.com/spf13/cobra.(*Command).execute(0x24ca3c0, 0x24f6578, 0x0, 0x0, 0x24ca3c0, 0x24f6578)
	/Users/justind/go/src/github.com/spf13/cobra/command.go:624 +0x23d
github.com/spf13/cobra.(*Command).ExecuteC(0x24ca600, 0x24caa80, 0x24d2d60, 0x1d9a923)
	/Users/justind/go/src/github.com/spf13/cobra/command.go:699 +0x2fe
github.com/spf13/cobra.(*Command).Execute(0x24ca600, 0x0, 0xc420129f48)
	/Users/justind/go/src/github.com/spf13/cobra/command.go:658 +0x2b
github.com/canopytax/ckube/cmd.Execute()
	/Users/justind/go/src/github.com/canopytax/ckube/cmd/root.go:25 +0x31
main.main()
	/Users/justind/go/src/github.com/canopytax/ckube/main.go:6 +0x20
```

### Steps to reproduce the behavior
Run `ckube nodes` with `kubectl` configured with a GKE cluster?  I'm not really sure but possibly need `k8s.io/client-go/plugin/pkg/client/auth/gcp`?

Thanks for the awesome tool!

**Comment by devonmoss** [comment]
importing `k8s.io/client-go/plugin/pkg/client/auth/gcp` [fixed](https://github.com/CanopyTax/ckube/commit/9968074538c4a11ac31fec6381ce120f81a50866) the issue for me. Thanks! [v0.4.2](https://github.com/CanopyTax/ckube/releases/tag/v0.4.2) contains the fix.

**Comment by domingusj** [comment]
Awesome! Confirmed it fixed it for me as well. Thanks again!
